server:
  port: 3344

spring:
  application:
    name: springcloud-config-server

  cloud:      #连接远程仓库
    config:
      server:
        git:
          uri: https://github.com/Jameszcx98/springcloud-config.git #https
          default-label: main #通过 config-server可以连接到git，访问其中的资源以及配置